language: shell

os: osx
osx_image: xcode11.3
env: ROS_DISTRO=melodic \
     ROS_CONFIGURATION=desktop_full

install:
  - ./venv.sh

script:
  - ./retrieve.sh

before_cache:
  - brew cleanup

cache:
  directories:
  - "$HOME/.ros/rosdep"
  - "$HOME/Library/Caches/pip"
  - "$TRAVIS_BUILD_DIR/src"
  - "$TRAVIS_BUILD_DIR/src/rosdep-venv"

before_deploy:
  - ./package.sh

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: src.tar.xz
  on:
    repo: hguandl/ros-src-snapshot
    tags: true
