language: shell

os: osx
osx_image: xcode11.3
env: ROS_DISTRO=melodic \
     ROS_CONFIGURATION=desktop_full

install:
  - ./bootstrap.sh

script:
  - ./retrieve.sh

cache:
  directories:
  - "/etc/ros/rosdep"
  - "$HOME/.ros/rosdep"
  - "$HOME/Library/Caches/pip"
  - "$TRAVIS_BUILD_DIR/src"

before_deploy:
  - ./package.sh
  - shasum -a 256 ros-${TRAVIS_TAG}.tar.xz > ros-${TRAVIS_TAG}.tar.xz.sha256

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: ros-${TRAVIS_TAG}.tar.xz
  cleanup: false
  on:
    repo: hguandl/ros-src-snapshot
    tags: true
  release_notes_file: ros-${TRAVIS_TAG}.tar.xz.sha256
  edge: true
